# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nullapt < Formula
  desc "The private-first package manager for AI skills"
  homepage "https://nullapt.dev"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nullapt/nullapt/releases/download/v0.1.1/nullapt_0.1.1_darwin_amd64.tar.gz"
      sha256 "a08ec06eb1f9355cc9169a1c9f72eaeaf2850d4620042d88a8b53a455d56076f"

      define_method(:install) do
        bin.install "nullapt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nullapt/nullapt/releases/download/v0.1.1/nullapt_0.1.1_darwin_arm64.tar.gz"
      sha256 "63037ca8b44834a782a6250fecbc7f91c88c52372903fcc3747d1c1dcb2f9f7b"

      define_method(:install) do
        bin.install "nullapt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nullapt/nullapt/releases/download/v0.1.1/nullapt_0.1.1_linux_amd64.tar.gz"
      sha256 "e8a45363903f43e7fdd6e1e07c425083e6173a239c9182cc5ed61b26205f6fcd"
      define_method(:install) do
        bin.install "nullapt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nullapt/nullapt/releases/download/v0.1.1/nullapt_0.1.1_linux_arm64.tar.gz"
      sha256 "269ddb170b90a830f7f255aa430f7653d8f5ebd7e51a493d2d61c54d75ac3d7b"
      define_method(:install) do
        bin.install "nullapt"
      end
    end
  end

  test do
    system "#{bin}/nullapt --version"
  end
end
